import "./globals.css";
import type { Metadata } from "next";
import { sfProDisplay, sfProText } from "@/lib/font";
import StyledComponentsRegistry from "@/lib/registry";
import CommonLayout from "@/components/common/CommonLayout";
import { AppContextProvider } from "@/lib/AppContextProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sfProText.variable} ${sfProDisplay.variable}`}>
        <AppContextProvider>
          <StyledComponentsRegistry>
            <CommonLayout>{children}</CommonLayout>
          </StyledComponentsRegistry>
        </AppContextProvider>
      </body>
    </html>
  );
}
