import "./globals.css";
import type { Metadata } from "next";
import { sfProDisplay, sfProText } from "@/lib/font";
import StyledComponentsRegistry from "@/lib/registry";
import CommonLayout from "@/components/common/CommonLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${sfProText.variable} ${sfProDisplay.variable}`}>
        <StyledComponentsRegistry>
          <CommonLayout>{children}</CommonLayout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
